extends Resource
const DISPLAY_NAMES: Dictionary = {
	"AssistAttack": "D",
	"AssistAttack2": "Down D",
	"AssistSuper": "Down DownRight Right D",
	"AssistAirAttack": "D UI_COMBO_WORD_AIR",
	"AssistAirAttack2": "Down D UI_COMBO_WORD_AIR",
	"AssistAirSuper": "Down DownRight Right D UI_COMBO_WORD_AIR",
	"AssistAirSuperFollowup": "UI_COMBO_WORD_RELEASE D", # A.Oga's super
	
	"GroundThrowHit": "Right A + D",
	"GroundBackThrowHit": "Left A + D",
	"AirThrowHit": "A + D UI_COMBO_WORD_AIR", "AngelAirThrowHit": "A + D UI_COMBO_WORD_AIR",
	"Stand5A": "A", "AngelHH2": "A", "AngelHH5": "A", "AngelHH7": "A",
	"Stand6A": "Right A", "AngelStand6A": "Right A",
	"StandcB": "B UI_COMBO_WORD_CLOSE", "AngelStandcB": "B UI_COMBO_WORD_CLOSE",
	"Stand5B": "B", "AngelHH4": "B", "AngelHH8": "B",
	"Stand5C": "C", "AngelHH3": "C", "AngelHH6": "C", "AngelStand5C": "C",
	"Stand6C": "Right C", "AngelStand6C": "Right C",
	"Crouch2A": "Down A", "AngelCrouch2A": "Down A",
	"Crouch2B": "Down B", "AngelCrouch2B": "Down B", 
	"Crouch2C": "Down C", "AngelCrouch2C": "Down C",
	"Crouch3C": "DownRight C", "AngelCrouch3C": "DownRight C",
	"Jump5A": "A UI_COMBO_WORD_AIR", "AngelJump5A": "A UI_COMBO_WORD_AIR",
	"Jump5B": "B UI_COMBO_WORD_AIR", "AngelJump5B": "B UI_COMBO_WORD_AIR",
	"Jump2C": "Down C UI_COMBO_WORD_AIR", "AngelJump2C": "Down C UI_COMBO_WORD_AIR",
	"Jump5C": "C UI_COMBO_WORD_AIR", "AngelJump5C": "C UI_COMBO_WORD_AIR",
	"Jump6B": "Right B UI_COMBO_WORD_AIR",
	"Jump6C": "Right C UI_COMBO_WORD_AIR",
	"Jump8C": "Up C UI_COMBO_WORD_AIR",
	"DuckPunch": "Right Down DownRight B UI_COMBO_WORD_AIR_OK", 
	"MioCards":"Right Down DownRight X UI_COMBO_WORD_AIR_OK",
	"SubaruStarBall": "Down DownRight Right A UI_COMBO_WORD_AIR_OK",
	"Stinger": "Down DownLeft Left B",
	"AirStinger": "Down DownLeft Left B UI_COMBO_WORD_AIR",
	"BionicArm": "Right DownRight Down DownLeft Left Right C", "AngelBionicArm": "Right DownRight Down DownLeft Left Right C",
	"AngelInstall": "Down DownLeft Left Down DownLeft Left C",
	"AngelHH1": "Right DownRight Down DownLeft Left Right A",
	"AngelHH9": "Down DownLeft Left C",
	"AngelHH10": "Down DownRight Right D",
	
	"SummonHato": "Down DownRight Right X",
	"Hato5A": "UI_COMBO_WORD_RELEASE A",
	"Hato5B": "UI_COMBO_WORD_RELEASE B",
	"Hato5C": "UI_COMBO_WORD_RELEASE C UI_COMBO_WORD_AIR_OK",
	"HatoCards": "Down DownRight Right UI_COMBO_WORD_RELEASE C UI_COMBO_WORD_AIR_OK",

	"MediumDP": "Right Down DownRight B",
	"Snapback": "Down DownLeft Left C",

	"LightYoruMatsuyo": "Down DownLeft Left A UI_COMBO_WORD_AIR_OK",
	"YoruMatsuyo": "Down DownLeft Left B UI_COMBO_WORD_AIR_OK",
	"CaramelThrust": "Down DownRight Right A UI_COMBO_WORD_OR B",
	"AirCaramelThrust": "Down DownRight Right A UI_COMBO_WORD_OR B UI_COMBO_WORD_AIR",
	"GatoKick": "   ↪ A",
	"AngelJump2B": "Down B UI_COMBO_WORD_AIR",
	"Stance": "C UI_COMBO_WORD_CHANGE",
	"Scissors": "Right DownRight Down DownLeft Left A",

	
	"OllieRook": "UI_COMBO_WORD_RELEASE A",
	"SetOllieRook": "Down DownLeft Left UI_COMBO_WORD_TAP A UI_COMBO_WORD_AIR_OK",
	"OllieChargeRook": "UI_COMBO_WORD_RELEASE A (UI_COMBO_WORD_ENHANCED)",
	"SetOllieChargeRook": "Down DownLeft Left UI_COMBO_WORD_HOLD A UI_COMBO_WORD_AIR_OK",
	"OllieChargeKnight": "UI_COMBO_WORD_RELEASE C (UI_COMBO_WORD_ENHANCED)",
	"SetOllieChargeKnight": "Down DownLeft Left UI_COMBO_WORD_HOLD C UI_COMBO_WORD_AIR_OK",
	"OllieProtonCannon": "Down DownRight Right C",

	"KanataAirFiftyKGHit": "Right DownRight Down DownLeft Left A UI_COMBO_WORD_AIR",
	"KanataFiftyKGHit": "Right DownRight Down DownLeft Left A",
	"KanataAirFiftyRekkaA": "Right DownRight Down DownLeft Left A",
	
	"KanataSuperFiftyRekkaA":"Right DownRight Down DownLeft Left C",
	
	"KanataWingStanceEnter":"Down DownRight Right X",
	"KanataWingStanceC":"   ↪ C",
	"KanataWingStanceB":"   ↪ B",
	
	"GrappleFollowUp": "Down DownRight Right A UI_COMBO_WORD_OR B UI_COMBO_WORD_AIR_OK",
	"AirGrapple": "Down DownRight Right A UI_COMBO_WORD_OR B UI_COMBO_WORD_AIR",
	"Grapple": "Down DownRight Right A or B",
	"Flight5A": "A UI_COMBO_WORD_FLIGHT",
	"Flight5BEarly": "B UI_COMBO_WORD_FLIGHT",
	"Flight5CEarly": "C UI_COMBO_WORD_FLIGHT",
	"Flight8C": "Up C UI_COMBO_WORD_FLIGHT",
	"Flight2CIncrease": "UI_COMBO_WORD_HOLD Down C",
	"FlightEnter": "Down DownLeft Left X",
	"DeusExMachina": "Down DownRight Right C",
	"AirStomp": "Down DownRight Right C UI_COMBO_WORD_AIR",
	"RyukenShiki": "Right Down DownRight A UI_COMBO_WORD_OR B UI_COMBO_WORD_AIR_OK",

	"HammerStartup" : "UI_COMBO_WORD_TAP D UI_COMBO_WORD_THEN UI_COMBO_WORD_HOLD Left",
	"HammerFollowup" : "UI_COMBO_WORD_RELEASE Left UI_COMBO_WORD_EARLY",
	"HammerJustFollowup" : "UI_COMBO_WORD_RELEASE Left UI_COMBO_WORD_PERFECT",
	"AirHammerFollowup" : "UI_COMBO_WORD_RELEASE Left UI_COMBO_WORD_AIR UI_COMBO_WORD_EARLY",
	"AirHammerJustFollowup" : "UI_COMBO_WORD_RELEASE Left UI_COMBO_WORD_AIR UI_COMBO_WORD_PERFECT",
	"JumpStartup" : "UI_COMBO_WORD_TAP D UI_COMBO_WORD_THEN UI_COMBO_WORD_HOLD Down",
	"JumpFollowup" : "UI_COMBO_WORD_RELEASE Down UI_COMBO_WORD_EARLY",
	"JumpJustFollowup" : "UI_COMBO_WORD_RELEASE Down UI_COMBO_WORD_PERFECT",
	"AssistAirSuperAttack" : "UI_COMBO_WORD_RELEASE X",

	"AssistSubaruStarBall": "D",
	
	"Assist5B": "UI_COMBO_WORD_RELEASE B",
	"Assist5C": "UI_COMBO_WORD_RELEASE C",

	"AirSuperCharge1": "UI_COMBO_WORD_RELEASE D (UI_COMBO_WORD_CHARGE 1)",
	"AirSuperCharge2": "UI_COMBO_WORD_RELEASE D (UI_COMBO_WORD_CHARGE 2)",
	"AirSuperCharge3": "UI_COMBO_WORD_RELEASE D (UI_COMBO_WORD_CHARGE 3)",
	"HakkaTags": "D",

	"ASuicoAssistAirAttack2": "Down D UI_COMBO_WORD_STANCE UI_COMBO_WORD_AIR",
	"ASuicoAssistAttack2": "Down D UI_COMBO_WORD_STANCE",
	"ASuicoAssistAirAttack": "D UI_COMBO_WORD_STANCE UI_COMBO_WORD_AIR",
	"ASuicoAssistAttack": "D UI_COMBO_WORD_STANCE",
}
