extends Resource

const COMBOS := [ #Sample Subaru Combos
    {0: "Jump5C", #spammable button into knockdown
    1: "Crouch2B",
    2: "Crouch2C",
    3: "DUMMY: [i] \nHint: Use Jump5C as you are falling."},
    {0: "Crouch2A", #chain into knockdown
    1: "StandcB",
    2: "Stand5C",
    3: "Crouch2C"},
    {0: "SubaruStarBall",
    1: "DUMMY: [i] \nHint: Quickly move the directions first and then press the attack button!"}, #motion input
    {0: "Crouch2B", #special cancel
    1:"Stinger",
    2:"DUMMY: [i] \nHint: You can start preparing the directions for the special move as Down B is happening.\n\nThe Down in Crouch2B counts for Stinger !"},
    {
    0:"Crouch3C", #universal anti air combo into air throw
    1:"DUMMY: [i] jump [/i]",
    2:"Jump5A",
    3:"Jump5B",
    4:"Jump5C",
    5:"DUMMY: [i] double jump [/i]",
    6:"AirThrowHit",
    7: "DUMMY: [i] \nHint: Hit up as soon as you hit the opponent! [/i]"},
    {0:"Crouch2A", #universal air combo into special
    1:"StandcB",
    2:"Crouch3C",
    3:"DUMMY: [i] jump [/i]",
    4:"Jump5A",
    5:"Jump5B",
    6:"Jump5C",
    7:"DUMMY: [i] double jump [/i]",
    8:"Jump5B",
    9:"Jump5C",
    10:"DuckPunch"},
    {0: "GroundThrowHit",
    1: "DUMMY: A + B + C [i] during throw hit [/i]",
    2: "Jump5B",
    3: "Jump5C",
    4: "AirStinger"},
    {0: "BionicArm",
    1: "BionicArm"},
    {0: "DUMMY: AngelInstall",
    1: "AngelHH1",
    2: "AngelHH1",
    3: "AngelHH2",
    4: "AngelHH3",
    5: "AngelHH4",
    6: "AngelHH5",
    7: "AngelHH6",
    8: "AngelHH7",
    9: "AngelHH8",
    10: "AngelHH9",
    11: "AngelHH9",
    12: "AngelHH10",
    13: "AngelHH10"
},
	{0: "Stand5A",
	1: "StandcB",
	2: "Crouch3C",
	3: "DUMMY:[i] instant air dash [/i]",
	4: "Jump2C",
	5: "Jump5B",
	6: "Jump5C",
	7: "Jump2C",
	8: "Jump5B",
	9: "Jump5C",
	10: "Jump2C",
	11: "Jump5B",
	12: "Jump5C",
	13: "Jump2C",
	14: "SubaruStarBall",
	15: "DUMMY: [i] landing cancel [/i]",
	16: "StandcB",
	17: "Stand5C",
	18: "Stand6C",
	19: "BionicArm",
	20: "BionicArm",
	21: "DUMMY: [i] \nHint: try and air dash as fast as possible! [/i]"}
]