extends Resource

const COMBOS: Dictionary = { # Sample Subaru Combos
	Enums.PointCharacters.Subaru: [
	{0: "Jump5C", # spammable button into knockdown
	1: "Crouch2B",
	2: "Crouch2C",
	3: "DUMMY: [i] \nHint: Use Jump5C as you are falling."},
	{0: "Crouch2A", # chain into knockdown
	1: "StandcB",
	2: "Stand5C",
	3: "Crouch2C"},
	{0: "SubaruStarBall",
	1: "DUMMY: [i] \nHint: Quickly move the directions first and then press the attack button!"}, # motion input
	{0: "Crouch2B", # special cancel
	1: "Stinger",
	2: "DUMMY: [i] \nHint: You can start preparing the directions for the special move as Crouch2B is happening.\n\nThe Down in Crouch2B counts for Stinger !"},
	{
	0: "Crouch3C", # universal anti air combo into air throw
	1: "DUMMY: [i] jump [/i]",
	2: "Jump5A",
	3: "Jump5B",
	4: "Jump5C",
	5: "DUMMY: [i] double jump [/i]",
	6: "AirThrowHit",
	7: "DUMMY: [i] \nHint: Hit up as soon as you hit the opponent! [/i]"},
	{0: "Crouch2A", # universal air combo into special/knockdown
	1: "StandcB",
	2: "Crouch3C",
	3: "DUMMY: [i] jump [/i]",
	4: "Jump5A",
	5: "Jump5B",
	6: "Jump5C",
	7: "DUMMY: [i] double jump [/i]",
	8: "Jump5B",
	9: "Jump5C",
	10: "DuckPunch"},
	{0: "GroundThrowHit",
	1: "DUMMY: A + B + C [i] during throw hit [/i]",
	2: "Jump5B",
	3: "Jump5C",
	4: "AirStinger"},
	{0: "BionicArm",
	1: "BionicArm"},
	{0: "DUMMY: [color=yellow]Corner Only[/color] [i] \nHint: Land and jump again after each Jump2C ! [/i]",
	1: "StandcB",
	2: "Stand5C",
	3: "Crouch3C",
	4: "Jump5B",
	5: "Jump5C",
	6: "Jump2C",
	7: "Jump5B",
	8: "Jump5C",
	9: "Jump2C",
	10: "Jump5B",
	11: "Jump5C",
	12: "Jump2C",
	13: "Jump5B",
	14: "Jump5C",
	15: "Jump2C",
	16: "Stand5B",
	17: "Stand5C",
	18: "Stinger",
	},
	{0: "DUMMY: AngelInstall",
	1: "AngelHH1",
	2: "AngelHH1",
	3: "AngelHH2",
	4: "AngelHH3",
	5: "AngelHH4",
	6: "AngelHH5",
	7: "AngelHH6",
	8: "AngelHH7",
	9: "AngelHH8",
	10: "AngelHH9",
	11: "AngelHH9",
	12: "AngelHH10",
	13: "AngelHH10"
	},
	{0: "Stand5A",
	1: "StandcB",
	2: "Crouch3C",
	3: "DUMMY:[i] instant air dash [/i]",
	4: "Jump2C",
	5: "Jump5B",
	6: "Jump5C",
	7: "Jump2C",
	8: "Jump5B",
	9: "Jump5C",
	10: "Jump2C",
	11: "Jump5B",
	12: "Jump5C",
	13: "Jump2C",
	14: "SubaruStarBall",
	15: "DUMMY: [i] landing cancel [/i]",
	16: "StandcB",
	17: "Stand5C",
	18: "Stand6C",
	19: "BionicArm",
	20: "BionicArm",
	21: "DUMMY: [i] \nHint: try and air dash as fast as possible! [/i]"
	},
	{
	0: "DUMMY: [i] Hint: The first Jump6C requires a [color=yellow]clean hit[/color]. Good Luck! [/i]",
	1: "Jump6C",
	2: "DUMMY: AngelInstall",
	3: "DUMMY: [i] hold Left [/i]",
	4: "AngelStand5C",
	5: "DUMMY: [i] delay [/i]",
	6: "AngelStand5C",
	7: "AngelCrouch3C",
	8: "DUMMY: [i] ground bounce after each air move [/i]",
	9: "AngelJump5A",
	10: "AngelJump5B",
	11: "AngelJump5A",
	12: "DUMMY: [i] delay jump [/i]",
	13: "AngelAirThrowHit",
	14: "AngelBionicArm",
	15: "AngelBionicArm",
	16: "AngelBionicArm",
	17: "DUMMY: A + B + C",
	18: "Jump2C",
	19:"AngelStand6A",
	20: "AngelHH1",
	21: "AngelHH1",
	22: "AngelHH2",
	23: "AngelHH3",
	24: "AngelHH4",
	25: "AngelHH5",
	26: "AngelHH6",
	27: "AngelHH7",
	28: "AngelHH8",
	29: "AngelHH9",
	30: "AngelHH9",
	31: "AngelHH10",
	32: "AngelHH10"
	},
],

Enums.PointCharacters.Mio: [
	{0: "Jump5C", # spammable button into knockdown
	1: "Crouch2B",
	2: "Crouch2C",
	3: "DUMMY: [i] \nHint: Use Jump5C as you are falling."},
	{0: "Crouch2A", # chain into knockdown
	1: "StandcB",
	2: "Stand5C",
	3: "Crouch2C",
	4: "Stand6C"},
	{0: "MioCards",
	1: "DUMMY: [i] \nHint: Quickly move the directions first and then press the attack button!"},
	{0: "Crouch2B", # special cancel
	1: "Stand6C",
	2: "MioCards",
	3: "DUMMY: [i] \nHint: You can start preparing the directions for the special move as Stand6C is happening.\n\nThe Right in Stand6C counts for MioCards !"},
	{
	0: "Crouch3C", # universal anti air combo into air throw
	1: "DUMMY: [i] jump [/i]",
	2: "Jump5A",
	3: "Jump5B",
	4: "Jump5C",
	5: "DUMMY: [i] double jump [/i]",
	6: "AirThrowHit",
	7: "DUMMY: [i] \nHint: Hit up as soon as you hit the opponent! [/i]"},
	{0: "Crouch2A", # universal air combo into special
	1: "StandcB",
	2: "Crouch3C",
	3: "DUMMY: [i] jump [/i]",
	4: "Jump5B",
	5: "Jump5B",
	6: "Jump5C",
	7: "DUMMY: [i] double jump [/i]",
	8: "Jump5A",
	9: "Jump5C",
	10: "Jump2C"},
	{0: "DUMMY: [i] \nHint: Hatotaurus attacks when you [color=yellow]release[/color] attack buttons! [/i]",
	1: "DUMMY: SummonHato",
	2: "DUMMY: Hold C",
	3: "DUMMY: Release C",
	4: "Stand5C",
	5: "Stand5C",
	6: "Stand5C",
	7: "Stand5C",
	8: "Stand5C",
	9: "Stand5C"},
	{0: "GroundThrowHit",
	1: "DUMMY: A + B + C [i] during throw hit [/i]",
	2: "Stand5B",
	3: "Stand5C",
	4: "Stand6C",
	5: "DUMMY: [i] Bonus: SummonHato [/i]"},
	{0: "DUMMY: SummonHato",
	1: "GroundThrowHit",
	2: "DUMMY: Hold GroundThrowHit",
	3: "DUMMY: Hold B",
	4: "DUMMY: Release B",
	5: "Stand5B",
	6: "Jump5B",
	7: "Jump5B",
	8: "DUMMY: Hold B",
	9: "Jump5C",
	10: "DUMMY: Release B",
	11: "Stand5B"},
	{0: "DUMMY: SummonHato",
	1: "DUMMY: Hold C",
	2: "HatoCards",
	3: "HatoCards",
	4: "HatoCards"},
],
Enums.PointCharacters.Oga: [
	{0: "Jump5B", # spammable button into knockdown
	1: "Crouch2B",
	2: "Crouch2C",
	3: "DUMMY: [i] \nHint: Use Jump5B as you are falling."},
],
Enums.PointCharacters.Ollie: [
	{0: "Crouch2C"},
	{0: "Stand5C",
	1: "Stand6A",
	2: "Crouch3C",
	3: "DUMMY: [i] jump [/i]",
	4: "Jump5A",
	5: "Jump5A",
	6: "Jump5B",}
],
Enums.PointCharacters.Suisei: [
	{0: "Jump5B",
	1: "Crouch2B",
	2: "DUMMY: [i] \nHint: Use Jump5B as you are falling."},
	{0: "Crouch2B",
	1: "DUMMY: YoruMatsuyo",
	2: "GatoKick",
	3: "DUMMY: Stance",
	4: "AngelJump2B",
	5: "DUMMY: Stance",
	6: "DUMMY: YoruMatsuyo",
	7: "GatoKick",
	8: "DUMMY: Stance",
	9: "AngelJump2B",
	10: "DUMMY: Stance",
	11: "AirThrowHit",
	12: "DUMMY: Stance",
	13: "AngelAirThrowHit",
	14: "DUMMY: Stance",
	15: "DUMMY: [i] air dash [/i]",
	16: "AirCaramelThrust",
	17: "DUMMY: Stance",
	18: "AngelAirThrowHit",
	19: "DUMMY: Stance",
	20: "AirCaramelThrust"
}
],
Enums.PointCharacters.Kanata: [
	{0: "Jump5B", # spammable button into knockdown
	1: "Crouch2A",
	2: "Crouch2C",
	3: "DUMMY: [i] \nHint: Use Jump5B as you are falling."},
],
Enums.PointCharacters.Flayon: [
	{}
]}
