extends Resource
const DISPLAY_NAMES: Dictionary = {
	"GroundThrowHit": "Right A + D",
	"AirThrowHit": "A + D air", "AngelAirThrowHit": "A + D air",
	"Stand5A": "A", "AngelHH2": "A", "AngelHH5": "A", "AngelHH7": "A",
	"Stand6A": "Right A", "AngelStand6A": "Right A",
	"StandcB": "B close",
	"Stand5B": "B", "AngelHH4": "B", "AngelHH8": "B",
	"Stand5C": "C", "AngelHH3": "C", "AngelHH6": "C", "AngelStand5C": "C",
	"Stand6C": "Right C", "AngelStand6C": "Right C",
	"Crouch2A": "Down A",
	"Crouch2B": "Down B",
	"Crouch2C": "Down C",
	"Crouch3C": "DownRight C", "AngelCrouch3C": "DownRight C",
	"Jump5A": "A air", "AngelJump5A": "A air",
	"Jump5B": "B air", "AngelJump5B": "B air",
	"Jump2C": "Down C air",
	"Jump5C": "C air",
	"Jump6C": "Right C air",
	"DuckPunch": "Right Down DownRight B (air ok)", "MioCards":"Right Down DownRight B (air ok)",
	"SubaruStarBall": "Down DownRight Right A (air ok)",
	"Stinger": "Down DownLeft Left B",
	"AirStinger": "Down DownLeft Left B air",
	"BionicArm": "Right DownRight Down DownLeft Left Right C", "AngelBionicArm": "Right DownRight Down DownLeft Left Right C",
	"AngelInstall": "Down DownLeft Left Down DownLeft Left C",
	"AngelHH1": "Right DownRight Down DownLeft Left Right A",
	"AngelHH9": "Down DownLeft Left C",
	"AngelHH10": "Down DownRight Right D",
	"SummonHato": "Down DownRight Right B",
	"HatoCards": "Right Down DownRight Release C (air ok)",
	"LightYoruMatsuyo": "Down DownLeft Left A or B (air ok)",
	"AirCaramelThrust": "Down DownRight Right A or B (air ok)",
	"GatoKick": "   ↪ A",
	"AngelJump2B": "Down B air",
	"Stance": "C change"
}
